# -*- coding: utf-8 -*-
"""HCL assignments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DtoX8LsIbP4A1tsG_Nkd4Jc-pQUYYYla
"""

# 1.Print all prime numbers between input range (Ex – input 20 50, prints all prime numbers between 20 and 50).

print("Prime numbers between 20 and 50:")

for num in range(20, 51):
    if num > 1:
        for i in range(2, int(num**0.5) + 1):
            if num % i == 0:
                break
        else:
            print(num, end=" ")

print()

# 2.Factorial using recursion

def fact(n):
    if n==0 or n==1:
        return 1
    return n*fact(n-1)

n=int(input())
print(fact(n))

#3.Square of numbers using lambda

n=int(input())
square=lambda x: x**2
print(square(n))

#4.Find the second largest element in a list

arr=list(map(int,input().split()))
largest=float('-inf')
secondl=float('-inf')

for i in range(len(arr)):
    if arr[i]>largest:
        secondl=largest
        largest=arr[i]
    elif arr[i]>secondl and arr[i]!=largest:
        secondl=arr[i]
print(secondl)

#5.Count frequency of characters in a string

s=input()

freq={}

for ch in s:
    freq[ch]=freq.get(ch,0)+1

for ch,count in freq.items():
    print(f"{ch} : {count}")

#6.Calculate area of a circle using math library.

import math
r=float(input())
area = math.pi * r * r
print(area)

# 7.Reverse a string without using built‑in reverse

word=input()
rev=""
for i in word:
  rev=i + rev
print(rev)

#8.Remove duplicates from a list

my_list = [1, 2, 2, 3, 4, 4, 5]
unique_list = list(set(my_list))

print(unique_list)

#9.Merge two dictionaries

dict1 = {1: 10, 2: 20, 3: 30}
dict2 = {4: 40, 5: 50, 6: 60}

dict1.update(dict2)

print(dict1)

#10.Fibonacci series using recursion

def fibonacci(n):
    if n <= 1:
        return n
    return fibonacci(n - 1) + fibonacci(n - 2)

n = int(input("Enter number of terms: "))

for i in range(n):
    print(fibonacci(i), end=" ")