# -*- coding: utf-8 -*-
"""Numpy Assignem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ON7SRLrwjwZCMfUfC76O3HPCxqShU_pQ
"""

import numpy as np

"""### Question 1 – Student Marks Array
The marks obtained by five students in a subject are given as `[78, 65, 89, 56, 92]`. Create a NumPy array and display the array along with its basic properties.
"""

m = np.array([78, 65, 89, 56, 92])
print("Student Marks Array:", m)
print("Data Type:", m.dtype)
print("Shape:", m.shape)
print("Number of Dimensions:", m.ndim)
print("Size:", m.size)

"""### Question 2 – Student Marks Access
The marks of five students are stored in a NumPy array as `[72, 85, 64, 90, 76]`. Write a program to access and display specific student marks using NumPy indexing and slicing.
"""

m = np.array([72, 85, 64, 90, 76])
print("Original Marks Array:", m)
print("First student's mark:", m[0])
print("Third student's mark:", m[2])
print("Last student's mark:", m[-1])
print("Marks of first three students:", m[0:3])
print("Marks from second to fourth student:", m[1:4])
print("Marks from third student to end:", m[2:])

"""### Question 3 – Subject-wise Marks
The marks obtained by five students in three subjects are given below. Create a NumPy array to represent the data and reshape it into an appropriate matrix format.
`[78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92]`
"""

mf = np.array([78, 85, 90, 65, 72, 80, 88, 91, 84, 56, 62, 70, 95, 89, 92])
print("Flattened marks array:", mf)
mm = mf.reshape(5, 3)
print("\nReshaped Marks Matrix (5 Students x 3 Subjects):\n", mm)

"""### Question 4 – Internal and External Marks
The internal and external examination marks of five students are stored in two NumPy arrays. Write a program to calculate the final marks of each student using NumPy array operations.
"""

i = np.array([40, 35, 45, 30, 48])
e = np.array([60, 50, 70, 45, 80])

print("Internal Marks:", i)
print("External Marks:", e)

f = i + e
print("\nFinal Marks:", f)

"""### Question 5 – Pass Percentage Analysis
The marks obtained by five students are `[45, 78, 56, 32, 91]`. Using NumPy Boolean masking, identify the students who have secured 50 marks or above.
"""

m = np.array([45, 78, 56, 32, 91])
print("Original Marks:", m)

p = m >= 50
print("\nBoolean Mask (marks >= 50):", p)

p_m = m[p]
print("Marks of students who secured 50 or above:", p_m)

"""### Question 6 – Average Marks
The marks of five students in three subjects are represented using a NumPy matrix. Write a program to calculate the average marks of each student.
"""

mm = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
print("Marks Matrix (Students x Subjects):\n", mm)

a = np.mean(mm, axis=1)
print("\nAverage Marks for each student:", a)

"""### Question 7 – Class Performance Statistics
The marks obtained by five students are `[67, 82, 91, 74, 58]`. Using NumPy statistical functions, determine the total, average, highest, lowest, and standard deviation of the marks.
"""

import numpy as np

marks = np.array([67, 82, 91, 74, 58])

total = np.sum(marks)
average = np.mean(marks)
highest = np.max(marks)
lowest = np.min(marks)
std_dev = np.std(marks)

print("Total Marks:", total)
print("Average Marks:", average)
print("Highest Mark:", highest)
print("Lowest Mark:", lowest)
print("Standard Deviation:", std_dev)

"""### Question 8 – Subject-wise Performance
The marks of five students in three subjects are stored in a NumPy matrix. Write a program to calculate the total marks obtained in each subject using an appropriate axis operation.
"""

import numpy as np

marks = np.array([
    [75, 80, 85],
    [90, 88, 92],
    [65, 70, 68],
    [82, 85, 90],
    [58, 62, 60]
])

subject_totals = np.sum(marks, axis=0)

print("Subject-wise Total Marks:", subject_totals)

"""### Question 9 – Student-wise Performance
The marks of five students in three subjects are stored in a NumPy matrix. Write a program to calculate the total marks obtained by each student using an appropriate axis operation.
"""

import numpy as np

marks = np.array([
    [78, 85, 90],
    [88, 92, 79],
    [65, 70, 72],
    [95, 89, 94],
    [80, 84, 88]
])

total_marks = np.sum(marks, axis=1)

for i, total in enumerate(total_marks, start=1):
    print(f"Student {i}: Total Marks = {total}")

"""### Question 10 – Student Ranking
The total marks obtained by five students are `[245, 278, 219, 290, 256]`. Use NumPy sorting and indexing operations to arrange the marks in order and determine the ranking of the students.
"""

import numpy as np

marks = np.array([245, 278, 219, 290, 256])

sorted_marks = np.sort(marks)[::-1]
sorted_indices = np.argsort(marks)[::-1]

print("Sorted Marks (Highest to Lowest):", sorted_marks)
for rank, idx in enumerate(sorted_indices, start=1):
    print(f"Rank {rank}: Student {idx + 1} with {marks[idx]} marks")

"""### Question 11 – Duplicate Marks Analysis
The marks obtained by five students are `[85, 92, 85, 76, 92]`. Use NumPy functions to identify the unique marks obtained by the students.
"""

m = np.array([85, 92, 85, 76, 92])
print("Original Marks:", m)

u = np.unique(m)
print("\nUnique Marks obtained by students:", u)

"""### Question 12 – Missing Marks
The marks of five students are represented as `[78, 85, np.nan, 92, 67]`, where `np.nan` represents a missing mark. Write a NumPy program to calculate the average marks without considering the missing value.
"""

m = np.array([78, 85, np.nan, 92, 67])
print("Marks with missing value:", m)

a = np.nanmean(m)
print("\nAverage marks (ignoring missing values):", a)

"""### Question 13 – Grade Classification
The marks obtained by five students are `[95, 82, 74, 61, 45]`. Using NumPy conditional operations, classify the students into appropriate grade categories based on their marks.
"""

import numpy as np

marks = np.array([95, 82, 74, 61, 45])

conditions = [
    marks >= 90,
    (marks >= 75) & (marks < 90),
    (marks >= 60) & (marks < 75),
    marks < 60
]

grades_list = np.array(['A', 'B', 'C', 'F'])

grades = np.select(conditions, grades_list, default='-')

print("Marks:", marks)
print("Classified Grades:", grades)

"""### Question 14 – Random Marks Generation
Generate marks for five students using NumPy's random number generation functionality. Perform basic statistical analysis on the generated marks.
"""

g = np.random.randint(0, 101, size=5)
print("Generated Marks for 5 Students:", g)

print("\nStatistical Analysis of Generated Marks:")
print("Mean:", np.mean(g))
print("Median:", np.median(g))
print("Minimum:", np.min(g))
print("Maximum:", np.max(g))
print("Standard Deviation:", np.std(g))

"""### Question 15 – Student Performance Analysis
The marks of five students in three subjects are stored in a NumPy array. Develop a program to perform a complete student performance analysis by calculating the total marks, average marks, highest marks, lowest marks, and identifying students who perform above the class average.
"""

mm = np.array([
    [78, 85, 90],
    [65, 72, 80],
    [88, 91, 84],
    [56, 62, 70],
    [95, 89, 92]
])
print("Marks Matrix (Students x Subjects):\n", mm)

t = np.sum(mm, axis=1)
print("\nTotal Marks per Student:", t)

a = np.mean(mm, axis=1)
print("Average Marks per Student:", a)

h = np.max(mm, axis=1)
print("Highest Marks per Student:", h)

l = np.min(mm, axis=1)
print("Lowest Marks per Student:", l)

c = np.mean(mm)
print("\nOverall Class Average:", c)

aa = t > c

print("\nStudents performing above the class average (Boolean Mask):", aa)
print("Total Marks of students performing above class average:", t[aa])