# -*- coding: utf-8 -*-
"""py  function assignment .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sxSiM317GyA0Afx7aJJaNLmK4lb1yZ5d
"""

#1.Write a function calculate(a, b, operation) that performs addition, subtraction, multiplication, or division based on the supplied operation.

def calculate(a, b, operation):
    if operation == "+":
        return a + b
    elif operation == "-":
        return a - b
    elif operation == "*":
        return a * b
    elif operation == "/":
        return a / b
    else:
        return "Invalid operation"


a=int(input())
b=int(input())
operation=input()

print(calculate(a,b,operation))

#2.Write a function sum_numbers(*args) that accepts any number of arguments and returns their sum.

def sum_numbers(*args):
    return sum(args)
print(sum_numbers(1, 2, 3))
print(sum_numbers(10, 20, 30, 40))
print(sum_numbers())

#3.Write a function employee(**args) that accepts employee information such as name, ID, department and salary, then displays the information.

def employee(**args):
    for key, value in args.items():
        print(key, ":", value)

employee(name="Swaminathan.V", ID=100, department="IOT", salary=50000)

#4.Write a function remove_duplicates(lst) that returns a list containing only unique elements while preserving their original order.

def remove_duplicates(lst):
    result = []

    for item in lst:
        if item not in result:
            result.append(item)

    return result

print(remove_duplicates([1, 2, 2, 3, 1, 4, 3]))

#5.Using a lambda function, sort a list of tuples based on the second element. Example: [(1,5), (2,3), (4,1)].

data = [(1, 5), (2, 3), (4, 1)]
sorted_data = sorted(data, key=lambda x: x[1])
print(sorted_data)